config/routes.rb
Houselistings2::Application.routes.draw do
  resources :listings do
    collection do
      get 'update_all'
      put :update_attribute_on_the_spot
      get :get_attribute_on_the_spot
    end
  end

  resource :listings do
    member do
      put 'manual_update'
    end
  end

  

  match "/inbound_email/" => "inbound_email#create"
  root :to => 'listings#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :commentable_id, :commentable_type, :comments_attributes

  belongs_to :commentable, :polymorphic => true
  has_many :comments, :as => :commentable
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  attr_accessible :address, :url, :date_entered, :listed_price, :open_house_date, :map_url, :listed_description, :date_listed, :days_on_market, :notes_attributes, :property_rating, :active_flag

  has_many :notes, :dependent => :destroy
  has_many :photos
  has_many :comments, :as => :commentable
  accepts_nested_attributes_for :notes, allow_destroy: true

  validates :url, :presence => true
  before_validation :default_values

  def default_values
    self.active_flag  ||= 'true' if active_flag.nil?
    self.address      ||= 'Looking up...'
    self.date_entered ||= Time.now
    self.property_rating ||= '3'

  end


  def self.create_from_postmark(mitt)
    message_body = mitt.text_body
    from_email = mitt.from_email
    parsed_uri_array = URI.extract(message_body, "http")
    listings = Array.new
    if parsed_uri_array.present?
      parsed_uri_array.each do |single_parsed_uri|
        cleaned_uri = single_parsed_uri.to_s.gsub(/[*]/,'')
        listing = Listing.find_or_initialize_by_url(cleaned_uri)
        unless listing.notes.present?
          note = listing.notes.build(:note_text => "Sent via email from #{from_email}")
          note.save
        end
        listing.url = cleaned_uri
        listings.push(listing)
      end
      return listings
    else
      listing = Listing.new
      listings = [listing]
      return listings
    end
  end
end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :note_text, :note_author, :note_attributes
  belongs_to :listing
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :photo_url, :photo_attributes
  belongs_to :listing
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/inbound_email_controller.rb
class InboundEmailController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def create
    @listings = Listing.create_from_postmark(Postmark::Mitt.new(request.body.read))
    if @listings.present?
      @listings.each do |listing|
        if listing.url
          listing.save
          Resque.enqueue(FetchListingData, listing.id)
        end
      end
      render :text => "Created a Listing!", :status => :created
    else
      render :text => "Didn't Create a Listing!", :status => :created
    end
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  # GET /listings
  # GET /listings.json

  can_edit_on_the_spot

  def index
    @listings = Listing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @listings }
    end
  end

  def show
    @listing = Listing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @listing }
    end
  end

  def new
    @listing = Listing.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @listing }
    end
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def create
    @listing = Listing.find_or_initialize_by_url(params[:listing][:url])
    if @listing.persisted?
      notice_msg = 'Listing already exists. Here it is.'
    else
      notice_msg = 'New listing was successfully added.'
    end

    respond_to do |format|
      if @listing.save
        Resque.enqueue(FetchListingData, @listing.id)
        format.html { redirect_to @listing, notice: notice_msg }
        format.json { render json: @listing, status: :created, location: @listing }
      else
        format.html { render action: "new" }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @listing = Listing.find(params[:id])

    respond_to do |format|
      if @listing.update_attributes(params[:listing])
        if (params[:commit] != "Add Note") && (params[:commit] != "Manually Update") && (params[:commit] != "Add")
          Resque.enqueue(FetchListingData, @listing.id)
          format.html { redirect_to @listing, notice: 'Listing is being updated in the background.' }
          format.json { head :no_content }

        elsif (params[:commit] == "Add")
            format.html { redirect_to :action => "index", notice: 'Added a new note.'}
            format.json { head :no_content }

        elsif (params[:commit] == "Manually Update")
          format.html { redirect_to @listing, notice: 'Listing was manually updated.' }
          format.json { head :no_content }

        elsif (params[:commit] == "Add Note")
          format.html { redirect_to @listing, notice: 'Listing was manually updated.' }
          format.json { head :no_content }

        elsif
          format.html { render action: "edit" }
          format.json { render json: @listing.errors, status: :unprocessable_entity }
        end
      end
    end
  end


  def update_all
    @listings = Listing.all

    @listings.each do |listing|
      Resque.enqueue(FetchListingData, listing.id)
    end
    flash[:notice] = 'Updating records in background.'
    redirect_to :action => 'index'
  end


  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy
    respond_to do |format|
      format.html{ redirect_to listings_url}
      format.xml { head :ok}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
  
end

app/helpers/inbound_email_helper.rb
module InboundEmailHelper
end

app/helpers/listings_helper.rb
module ListingsHelper

  def days_since_listed
    if @listing.date_listed
      number_days_since_listed = distance_of_time_in_words_to_now(@listing.date_listed, include_seconds = false)
    else
      number_days_since_listed = "Unknown"
    end
  end

  def open_house_helper
    if @listing.open_house_date.present?
      on_the_spot_edit @listing, :open_house_date
    else
      on_the_spot_edit @listing, :open_house_date
    end
  end

  def google_map_helper
    google_map_link = "http://maps.google.com/maps?q=#{@listing.address}"
  end

  def date_entered_formatted(listing)
    if listing.date_entered.present?
      date_listed = listing.date_entered.to_formatted_s(:long)
    end
  end

  def days_since_updated
    if @listing.date_entered.present?
      number_days_since_updated = "(#{time_ago_in_words(@listing.updated_at, Time.now)} ago.)"
    else
      number_days_since_updated = ""
    end
  end

  def show_notes_index(listing)
    if listing.notes.present?
      truncate(listing.notes.last.note_text, :length =>100, :separator => ' ')
    else
      return
    end
  end

  def add_note_from_index (listing)
    semantic_form_for listing do |f|
      f.inputs do
        link_to_add_association 'New', f, :notes, :partial => 'short_note_fields'
      end
    end
  end


  def show_notes_full
    if @listing.notes.present?
      truncate(@listing.notes.last.note_text, :length =>500, :separator => ' ')
    else
      return
    end
  end

  def show_photo_if_exist
    if @listing.photos.present?
      photo_url = @listing.photos.last.photo_url
      return_html = "<a href='#{@listing.url}' target='_blank'><img src='#{photo_url}' ></a>"
      return return_html
    else
      return
    end
  end

  def show_photo_link_if_exist(listing)
    if listing.photos.present?
      photo_url = listing.photos.last.photo_url
      return_html = "<a href='#{listing.url}' class='screenshot' rel='#{photo_url}' target='_blank'> pic </a>"
      return return_html
    else
      return
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Houselistings2</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/listings/_form.html.erb
<%= semantic_form_for @listing do |f| %>
  <%= f.inputs do %>
    
    <%= f.input :address %>
    <%= f.input :active_flag, :label => "Active?" %>
    <%= f.input :url, :as => :url%>
    <%= f.input :date_entered %>
    <%= f.input :date_listed %>
    <%= f.input :listed_price %>
    <%= f.input :open_house_date %>
    <%= f.input :property_rating, :as => :radio, :collection => ["1", "2", "3", "4", "5"] %>
    <%= f.input :listed_description, :input_html => { :rows => 8, :cols => 60 } %>

    <h3> Notes </h3>
    <div id="notes">
      <%= f.semantic_fields_for :notes do |note| %>
        <%= render 'note_fields', :f => note %>
      <%end%>
        <div class="links">
          <%=link_to_add_association 'Add New Note', f, :notes%>
        </div>
    <% f.actions do %>
      <%= f.action :submit%>
    <% end %>
  <% end %>

  <div class="actions">
    <%= submit_tag "Manually Update"%>
  </div>
<%end%>

app/views/listings/_form_url_only.html.erb
<%= form_for(@listing) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <div class="field">
      <%= f.label :url %><br/>
      <%= f.url_field :url, :size => 75 %>
    </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listings/_note_fields.html.erb
<div class="nested-fields">
	<%= f.inputs do %>
		<%= f.input :note_text, :label => "New Note", :input_html => { :rows => 3, :cols => 40 } %>
		
	<% end %>
  <div class="actions">
    <%= submit_tag "Add Note"%>
    <%= link_to_remove_association "Cancel", f%>
  </div>
</div>

app/views/listings/_short_note_fields.html.erb
<div>
	<%= f.inputs do %>
		<%= f.input :note_text, :label => "Note", :input_html => { :rows => 2, :cols => 40 } %>
    <%= f.actions do %>
      <%= submit_tag "Add" %>
      <%= link_to_remove_association "cancel", f%>
    <% end %>

	<% end %>

</div>

app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render 'form' %>

<%= link_to 'Back', @listing %> |
<%= link_to 'List', listings_path %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Broker Bot</h1>

<select name="show_act_inact" id="show_act_inact">
    <option value="" selected="selected" >Show all</option>
    <optgroup label="Show only:">
        <option value="Active">Active</option>
        <option value="Inactive">Inactive</option>
    </optgroup>
</select>

<table id="listings" class="display">
  <thead>
    <tr>
      <th>Address</th>
      <th>Pic</th>
      <th>Price</th>
      <th>Date Entered</th>
      <th>Note</th>
      <th>Rating</th>
      <th>Active?</th>
    </tr>
  </thead>

<tbody>
  <% @listings.each do |listing| %>
    <tr>
      <td><%= link_to(listing.address, listing, :style => 'text-decoration: none')%> </td>
      <td><%= raw show_photo_link_if_exist(listing) %> </td>
      <td><%=number_to_currency(listing.listed_price, :precision => 0, :delimiter => ",")%></td>
      <td><%= listing.created_at.to_date.to_formatted_s(:long) %> </td>
      <td class="table_note"><%= show_notes_index(listing)%> <%= add_note_from_index(listing) %></td>
      <td><%= on_the_spot_edit listing, :property_rating, :type => :select, :data => [[1,"1"],[2,"2"],[3,"3"],[4,"4"],[5,"5"]]%> </td>
      <td><%= on_the_spot_edit listing, :active_flag, :type => :select, :data => [[true,"Active"], [false,"Inactive"]] %> </td

    </tr>
  <% end %>
</tbody>
</table>

<br />



<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>New listing</h1>

<%= render 'form_url_only' %>

<%= link_to 'Back', listings_path %>

app/views/listings/short_note_fields.html.erb
<div class="nested-fields">
	<%= f.inputs do %>
		<%= f.input :note_text, :input_html => { :rows => 2, :cols => 40 } %>

	<% end %>
  <div class="actions">
    <%= submit_tag "Add Note"%>
    <%= link_to_remove_association "Cancel", f%>
  </div>
</div>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <%= raw show_photo_if_exist %><br/>

  <b>Listing Address:</b>
  <%= on_the_spot_edit @listing, :address, :ok_text => "Yup", :tooltip => "Click me to edit.", :selected => "True" %><br/>

  <b>Listing Price:</b>
  <%= number_to_currency(@listing.listed_price, :precision => 0, :delimiter => ",")%><br/>

  <b>Listing URL:</b>
  <%= link_to(@listing.url, @listing.url, :target => '_blank')%><br/>

  <b>Open House Date:</b>
  <%= open_house_helper %><br/>

  <b>Days Listed (or since last price adjustment): </b>
  <%= days_since_listed %><br/>

  <b>Google Map Link:</b>
  <%= link_to("Map", google_map_helper, :target => '_blank')%> <br/>

  <b>Last Updated: </b>
  <%= date_entered_formatted(@listing) %>
  <%= days_since_updated %> <br/>
  <br/>

  <b>Active?</b>
  <%= on_the_spot_edit @listing, :active_flag, :type => :select, :data => [[true, 'Active'], [false, 'Inactive']] %> <br/>

  <b>Rating </b>
  <%= on_the_spot_edit @listing, :property_rating, :type => :select, :data => [[1,"1"],[2,"2"],[3,"3"],[4,"4"],[5,"5"]] %>
  <br/>

  <b>Most Recent Note: </b>
  <%= show_notes_full %><br/>




  <%= semantic_form_for @listing do |f| %>
  <%= f.inputs do %>

          <%=link_to_add_association 'Add New Note', f, :notes%>

    <% f.actions do %>
      <%= f.action :submit%>
    <% end %>
  <% end %>
<%end%>

</p>


<%= link_to('Manually Edit', edit_listing_path(@listing)) %> |
<%= link_to('Update via Web', @listing, method: :put) %> |
<%= link_to('Back to List', listings_path) %> |
<%= link_to('Delete', @listing, confirm: 'Are you sure?', method: :delete) %>